[[redirects]]
  from = "/keep-teaching"
  to = "https://keepteaching.ucsc.edu"
  status = 301
  headers = {X-From = "Netlify"}
  force = true

[[redirects]]
  from = "/returning-to-campus/download-worksite-signs/"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSfIWvy5HuA79kkwPw6jLovRw4_SYzUJHq0g7UPbxHLEgtp_hg/viewform"
  status = 301
  headers = {X-From = "Netlify"}
  force = true

[[redirects]]
  from = "/returning-to-campus/get-tested/"
  to = "https://healthcenter.ucsc.edu/services/covid19.html"
  status = 301
  headers = {X-From = "Netlify"}
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.ucsc.edu *.google-analytics.com ajax.googleapis.com *.googletagmanager.com use.fontawesome.com *.google.com *.netlify.com *.unpkg.com fonts.googleapis.com fonts.gstatic.com unpkg.com *.fontawesome.com visualizedata.ucop.edu;frame-src 'self' *.youtube.com *.google.com visualizedata.ucop.edu;object-src 'none';frame-ancestors 'self' *.google.com *.youtube.com;"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

