[[redirects]]
  from = "/keep-teaching"
  to = "https://keepteaching.ucsc.edu"
  status = 301
  headers = {X-From = "Netlify"}
  force = true
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' *.ucsc.edu; img-src 'self' *.ucsc.edu *.rackcdn.com *.google.com *.googleapis.com *.gstatic.com data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' data: *.google.com unpkg.com *.netlify.com www.google-analytics.com ajax.googleapis.com *.googletagmanager.com use.fontawesome.com *.ucsc.edu; style-src 'self' 'unsafe-inline' data: *.google.com fonts.googleapis.com fonts.gstatic.com unpkg.com *.fontawesome.com *.ucsc.edu; frame-src 'self' *.youtube.com; object-src 'none'; font-src 'self' fonts.gstatic.com;"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"

